project:
  type: website
  output-dir: docs

website:
  title: "Contents"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - resume.qmd
      - thesis.qmd
      - projects.qmd
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/andrew-d-kerr
        target: _blank
      - icon: github
        href: https://github.com/Wander03
        target: _blank
      - icon: envelope
        href: mailto:adkerr2001@gmail.com

format:
  html:
    theme:
      light: minty
      dark: superhero
    respect-user-color-scheme: true
    css: styles.css
    toc: true
    page-layout: full
